name: Update Star Chart

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-star-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install chart.js chartjs-node-canvas

      - name: Generate Star chart
        run: node scripts/generate-star-chart.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push chart
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add images/star-chart.png
          git commit -m "Update Star chart"
          git push
